# Example configuration file for re-classify tool
# This shows the new surround-regexp configuration and operator settings

# New surround regex patterns with substitution
surround-regexp:
  - start: if|while|for
    endings: [end$0, $0_end]  # e.g., "if" -> "endif" or "if_end"
  - start: begin
    endings: [end, finish]    # "begin" -> "end" or "finish"
  - start: function|proc
    endings: [end$0, $0_done] # e.g., "function" -> "endfunction" or "function_done"

# Legacy form patterns (for backward compatibility)
form-prefix-regexp:
  - return
  - break
  - continue

simple-label-regexp:
  - else
  - case
  - default

compound-label-regexp:
  - "else-if"
  - "case-[a-zA-Z]+"

# Operator configuration with precedence values
operator-regexp:
  - pattern: "\\+"
    prefix-prec: 6
    infix-prec: 6
    postfix-prec: 0
    
  - pattern: "-"
    prefix-prec: 6
    infix-prec: 6
    postfix-prec: 0
    
  - pattern: "\\*"
    prefix-prec: 0
    infix-prec: 5
    postfix-prec: 0
    
  - pattern: "/"
    prefix-prec: 0
    infix-prec: 5
    postfix-prec: 0
    
  - pattern: "="
    prefix-prec: 0
    infix-prec: 1
    postfix-prec: 0
    
  - pattern: "\\+\\+"
    prefix-prec: 8
    infix-prec: 0
    postfix-prec: 8
    
  - pattern: "--"
    prefix-prec: 8
    infix-prec: 0
    postfix-prec: 8
