# Example configuration file for re-classify tool
# This shows the new surround-regexp configuration and operator settings

# New surround regex patterns with substitution
surround-regexp:
  - start: if|while|for
    endings: [end$0, $0_end]  # e.g., "if" -> "endif" or "if_end"
