# Simple test configuration for re-classify tool

surround-regexp:
  - start: if|while
    endings: [end$0, $0_end]

operator-regexp:
  - pattern: "="
    prefix-prec: 0
    infix-prec: 1
    postfix-prec: 0
