name: Functional Tests

on:
  workflow_call:
    inputs:
      go-version:
        description: 'Go version to use'
        required: false
        type: string
        default: '1.25'
      os:
        description: 'Operating system to run on'
        required: false
        type: string
        default: 'ubuntu-latest'
  workflow_dispatch:
    inputs:
      go-version:
        description: 'Go version to use'
        required: false
        type: string
        default: '1.25'
      os:
        description: 'Operating system to run on'
        required: false
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        default: 'ubuntu-latest'

jobs:
  functest:
    runs-on: ${{ inputs.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        cache: false

    - name: Install Python3 and pip
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install pipx
      run: python -m pip install --user pipx

    - name: Install Poetry via pipx
      run: pipx install poetry

    - name: Install just task runner
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/bin
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Build Go binary
      run: go build -o re-classify ./cmd/re-classify

    - name: Install Python dependencies
      run: poetry install

    - name: Run functional tests
      run: just functest