name: Functional Tests

on:
  workflow_call:
    inputs:
      go-version:
        description: 'Go version to use'
        required: false
        type: string
        default: '1.25'
      os:
        description: 'Operating system to run on'
        required: false
        type: string
        default: 'ubuntu-latest'
  workflow_dispatch:
    inputs:
      go-version:
        description: 'Go version to use'
        required: false
        type: string
        default: '1.25'
      os:
        description: 'Operating system to run on'
        required: false
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        default: 'ubuntu-latest'

jobs:
  functest:
    runs-on: ${{ inputs.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        cache: false

    - name: Install Python3 and pip
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-venv python3-pip

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Install just
      run: |
        if command -v just >/dev/null 2>&1; then
          echo "just already installed at $(command -v just); skipping install"
        else
          mkdir -p "$HOME/.local/bin"
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        fi

    - name: Run functional tests
      run: just functest
